import { useEffect, useRef, useState } from "react";
import type { Feature, FeatureCollection, Point } from "geojson";
import * as maplibregl from "maplibre-gl";
import type { GeoJSONSource, Map, StyleSpecification } from "maplibre-gl";
import { Protocol } from "pmtiles";
import "maplibre-gl/dist/maplibre-gl.css";

type Props = { id: string; name_ja: string; name_en: string | null; category: string; area: string | null; official_url: string | null; price_min_jpy: number | null; price_max_jpy: number | null; price_note: string | null; exhibition_starts_on: string | null; exhibition_ends_on: string | null; exhibition_period_note: string | null; description_ja: string | null; description_en: string | null };
export type LocationFeature = Feature<Point, Props>;
type Collection = FeatureCollection<Point, Props> & { returned: number };
const api = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000/api/v1";
const configuredStyleUrl = import.meta.env.VITE_MAP_STYLE_URL;
const styleUrl = configuredStyleUrl || (import.meta.env.DEV ? "https://gsi-cyberjapan.github.io/optimal_bvmap/style/std.json" : undefined);
const blankStyle: StyleSpecification = { version: 8, sources: {}, layers: [{ id: "background", type: "background", paint: { "background-color": "#e5edf2" } }] };
let registered = false;
const categoryLabel: Record<string, string> = { park: "公園", temple_shrine: "寺社", museum: "美術館・博物館", art_museum: "美術館", gallery: "畫廊", exhibition_space: "展覽空間", convention_center: "會展中心", zoo_aquarium: "動物園・水族館", food_shopping: "餐飲・購物", point_of_interest: "景點" };

function line(root: HTMLElement, label: string, value: string | null) { if (value) { const p = document.createElement("p"), b = document.createElement("strong"); b.textContent = `${label}　`; p.append(b, value); root.append(p); } }
function popup(p: Props) { const root = document.createElement("article"); root.className = "location-popup"; const h = document.createElement("h2"); h.textContent = p.name_ja; root.append(h); if (p.name_en) { const en = document.createElement("p"); en.className = "location-popup-en"; en.textContent = p.name_en; root.append(en); } const meta = document.createElement("p"); meta.className = "location-popup-meta"; meta.textContent = `${categoryLabel[p.category] ?? "景點"}${p.area ? ` · ${p.area}` : ""}`; root.append(meta); line(root, "說明", p.description_ja || p.description_en); const price = p.price_note || (p.price_min_jpy ? `¥${p.price_min_jpy.toLocaleString("ja-JP")}${p.price_max_jpy ? `–¥${p.price_max_jpy.toLocaleString("ja-JP")}` : ""}` : null); line(root, "價格", price); line(root, "展期", p.exhibition_period_note || (p.exhibition_starts_on ? `${p.exhibition_starts_on}${p.exhibition_ends_on ? ` ～ ${p.exhibition_ends_on}` : ""}` : null)); if (p.official_url) { const a = document.createElement("a"); a.href = p.official_url; a.target = "_blank"; a.rel = "noreferrer"; a.textContent = "官方網站 ↗"; root.append(a); } return root; }

export function EventMap({ onLocationsChange }: { onLocationsChange: (items: LocationFeature[]) => void }) {
  const element = useRef<HTMLDivElement>(null), mapRef = useRef<Map | null>(null); const [status, setStatus] = useState("載入東京景點中…"), [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!element.current || mapRef.current) return; if (!registered) { maplibregl.addProtocol("pmtiles", new Protocol().tile); registered = true; } const map = new maplibregl.Map({ container: element.current, style: styleUrl || blankStyle, center: [139.7671, 35.6812], zoom: 10, attributionControl: styleUrl ? {} : false }); map.addControl(new maplibregl.NavigationControl(), "top-right"); mapRef.current = map; map.on("error", (event) => setError(`底圖載入失敗：${event.error?.message ?? "未知錯誤"}`)); map.on("load", async () => { map.addSource("locations", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addLayer({ id: "location-points", type: "circle", source: "locations", paint: { "circle-color": ["match", ["get", "category"], "park", "#159e84", "temple_shrine", "#8b5aa3", "museum", "#d97706", "food_shopping", "#e95d75", "#2563eb"], "circle-radius": 6, "circle-stroke-color": "#fff", "circle-stroke-width": 1.5 } }); map.on("mouseenter", "location-points", () => { map.getCanvas().style.cursor = "pointer"; }); map.on("mouseleave", "location-points", () => { map.getCanvas().style.cursor = ""; }); map.on("click", "location-points", (event) => { const feature = event.features?.[0] as LocationFeature | undefined; if (feature) new maplibregl.Popup({ closeButton: true, maxWidth: "360px", offset: 14 }).setLngLat(feature.geometry.coordinates as [number, number]).setDOMContent(popup(feature.properties)).addTo(map); }); try { const r = await fetch(`${api}/locations`); if (!r.ok) throw Error(); const data = await r.json() as Collection; (map.getSource("locations") as GeoJSONSource).setData(data); onLocationsChange(data.features); setStatus(`${data.returned.toLocaleString("ja-JP")} 個東京景點 · 點擊圖示查看資訊`); } catch { setStatus("景點 API 尚未連線。請確認 backend 與 Supabase 設定。"); } }); return () => { map.remove(); mapRef.current = null; }; }, [onLocationsChange]);
  return <div className="map-panel"><div ref={element} className="map-canvas" /><p className="map-status">{status}</p>{error && <p className="map-hint">{error}</p>}</div>;
}
